# Generated by Django 4.0.2 on 2022-02-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='number',
        ),
    ]
